# Generated by Django 2.0.3 on 2018-04-15 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20180415_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='Exam_Type',
        ),
        migrations.RemoveField(
            model_name='results',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='totalmarks',
            name='T_Exam_Type',
        ),
        migrations.RemoveField(
            model_name='totalmarks',
            name='T_Year',
        ),
        migrations.AddField(
            model_name='results',
            name='Exam_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Admin.TotalMarks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalmarks',
            name='Exam_Type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalmarks',
            name='Year',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
