# Generated by Django 2.0.3 on 2018-04-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_auto_20180415_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='month',
            field=models.CharField(default='July', max_length=100),
            preserve_default=False,
        ),
    ]
